### ISSUE TITLE
[OS Keystone] Check the project in the response after succesfully validating a token value

### ISSUE THREAD

**Issue by arn3tt** [fogbow/resource-allocation-service#140]
See the [Keystone v3 API](https://developer.openstack.org/api-ref/identity/v3/#validate-and-show-information-for-token) for more info

**Comment by pauloewerton** [comment]
@arn3tt any news on this?

**Comment by fubica** [comment]
There is something related that could also be addressed in the context of this issue. Our OpenStack CloudIdentityProviderPlugin requires that the user informs: username, password, domain and projectname. This is required only if the site has been configured to use the OpenStackOneToOneMapper, since the projectname is needed by the interoperability plugins to access the cloud, and when the request is local, the CloudUser is generated by the mapper from the SystemUser that was generated during the interaction with the AS. Ideally, the OpenStackCloudIdentityProviderPlugin should be able to generate a user even if the projectname field is not passed (ex. this is how Horizon works). My suggestion is to have a single plugin that would check whether the needed credentials are passed. If either the username, the passowrd or the domain is not given, then an exception is thrown. Else, if a projectname is passed, than the current implementation is used, otherwise and alternative invocation is made to the cloud, using the syntax that does not require a projectname. This way, a site admin may configure the site to work with OpenStackAllToOneMapper and configure the GUI to ask only for username, password and domain (just like the user does when using an OpenStack cloud via Horizon).
